# -*- coding: utf-8 -*-
"""Python Mapeo de carpetas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12SoPlFOfv3n5sEZV8PztguTtJ54N49rd
"""

from collections import OrderedDict
import numpy as np

od=OrderedDict([('id', [['1asAAxceOHokaiBummHTdmPDs9Ldut2e3'], 
                     ['1asAAxceOHokaiBummHTdmPDs9Ldut2e3', '17wyd_xoepzijg33G6ePmUtnc__yhkZGp'], 
					 ['1asAAxceOHokaiBummHTdmPDs9Ldut2e3', '11eivubR60_5FgEM6wJXgYz_2ZGVLeVwl'], 
					 ['1asAAxceOHokaiBummHTdmPDs9Ldut2e3', '1tEEeQx5VZS0ObUnVZ0cODQtjf_DkqMQh'], 
					 ['1asAAxceOHokaiBummHTdmPDs9Ldut2e3', '1AF8kvGz0nyKL1VU-V2u7-W1uUrp_D35n'], 
					 ['1asAAxceOHokaiBummHTdmPDs9Ldut2e3', '11eivubR60_5FgEM6wJXgYz_2ZGVLeVwl', '1qZBDnKSZTiLo-DDFRkHp4fhDYtBjvCHU']]), 
		     ('names', ['RAIZ', 'PRIVADO', 'PUBLICO', 'RESERVADO', 'RESPALDO', 'ImageOther']), 
			 ('folders', ['1asAAxceOHokaiBummHTdmPDs9Ldut2e3', 
			              '17wyd_xoepzijg33G6ePmUtnc__yhkZGp', 
						  '11eivubR60_5FgEM6wJXgYz_2ZGVLeVwl', 
						  '1tEEeQx5VZS0ObUnVZ0cODQtjf_DkqMQh', 
						  '1AF8kvGz0nyKL1VU-V2u7-W1uUrp_D35n', 
						  '1qZBDnKSZTiLo-DDFRkHp4fhDYtBjvCHU'])])

"""# **Visualizando las claves del ordered dict**




"""

print("\nThis is an Ordered Dict:\n")
for key, value in od.items():
    print(key, value)

"""# **FUNCIÓN PARA MAPEAR CARPETAS**"""

def mapearCarpetas(od): 
  nombres=np.array(od['names'])
  id= np.array(od['id'], dtype=object)
  folders=np.array(od['folders'])
  objeto=np.array(od['id'], dtype=object)

  for i in range (len(nombres)):
    objeto[i]=(folders[i], nombres[i])

  for i in range(len(id)):
    for j in range(len(id[i])):
        if objeto[i][0]==id[i][j]:
           id[i][j]=objeto[i][1] 

        for g in range(len(objeto)):
           if objeto[g][0]==id[i][j]:
            id[i][j]=objeto[g][1] 

       #print(id[i][j])
       # print(i,j)

  for i in range(len(id)):
      id[i].insert(0,folders[i])


  return id

print(mapearCarpetas(od))